---
title: "Machine_Learning_Algorithms_Documentation"
author: "Geiser, Gruen, Hefti, Kuster"
date: "10/18/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Machine Learning Algorithms

# Dataset - German Housing Data 

load cleaned dataset
```{r}
data <- read.csv('germany_housing_cleaned.csv',header =T, sep=',', encoding='UTF-8')
head(data)
```

info
```{r}
str(data)
colnames(data)
```


## WEEK 1
# Linear Models

Simple linear regression

Data Visualisation

Plot Price ~ Rooms
```{r}
options(scipen=999) #block scientific notation

library(ggplot2)
#Rooms
ggplot(data, aes(Rooms, Price)) + geom_point()+ geom_smooth(method = lm, se = F, color= 'red')
ggplot(data, aes(Rooms, Price)) + geom_point(aes(size=Living_space, colour = factor(State)))
ggplot(data, aes(Rooms, Price)) + geom_bin2d(bins = 30)

#Living Space
ggplot(data, aes(Living_space, Price)) + geom_point() + geom_smooth(method = lm, se = F, color = 'red')




lm.price_rooms <- lm(Price ~ Rooms)
print(summary(lm.price_rooms))
```



```{r}

# use ggplot instead - to do
par(mfrow=c(2,1))
boxplot(Price ~ Type, main = 'Price ~ Type plotted with outliers')
boxplot(Price ~ Type, main = 'Price ~ Type plotted WITHOUT outliers', outline=FALSE)
```


```{r}
lm.type_rooms <- lm(Price ~ Type, data = data)
summary(lm.type_rooms)
```
